// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookQueryAPI.Models
{
    public partial class Book
    {
        public int ID { get; set; }
        public string 書名 { get; set; }
        public string 作者 { get; set; }
        public DateTime? 出版日期 { get; set; }
        public string 簡介 { get; set; }
    }
}